name: RDP Controller (Trigger, Wait, & Notify)

on:
  workflow_dispatch:
    inputs:
      target_range:
        description: 'Jalankan untuk repo mana? (Contoh: "1-5,8" atau "ALL")'
        required: true
        default: 'ALL'

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          input="${{ github.event.inputs.target_range }}"
          repos=""
          if [[ "$input" == "ALL" ]]; then
            input="1-20"
          fi
          IFS=',' read -ra RANGES <<< "$input"
          for range in "${RANGES[@]}"; do
            if [[ "$range" == *-* ]]; then
              start=$(echo "$range" | cut -d'-' -f1)
              end=$(echo "$range" | cut -d'-' -f2)
              for i in $(seq "$start" "$end"); do
                repos="$repos,\"WINDOWS$i\""
              done
            else
              repos="$repos,\"WINDOWS$range\""
            fi
          done
          repos=$(echo "$repos" | sed 's/^,//')
          echo "matrix={\"repo\":[$repos]}" >> $GITHUB_OUTPUT

  process-rdp-session:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: 1. Trigger Workflow
