name: Start On-Demand Bot Server

on:
  workflow_dispatch:

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Run the bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          ACTION_PAT: ${{ secrets.ACTION_PAT }} # Pastikan PAT juga ada di repo ini
          GITHUB_USER: ${{ secrets.USERNAME_GH }}
        run: python bot.py
