name: Stop RDP Sessions

on:
  workflow_dispatch:
    inputs:
      target_range:
        description: 'Hentikan repo mana? (Contoh: "5", "1-3,8", atau "ALL")'
        required: true
        default: 'ALL'

jobs:
  # Job 1: Membuat daftar repo yang akan dihentikan
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          input="${{ github.event.inputs.target_range }}"
          repos=""
          if [[ "$input" == "ALL" ]]; then
            input="1-20"
          fi

          IFS=',' read -ra RANGES <<< "$input"
          for range in "${RANGES[@]}"; do
            if [[ "$range" == *-* ]]; then
              start=$(echo "$range" | cut -d'-' -f1)
              end=$(echo "$range" | cut -d'-' -f2)
              for i in $(seq "$start" "$end"); do
                repos="$repos,\"WINDOWS$i\""
              done
            else
              repos="$repos,\"WINDOWS$range\""
            fi
          done

          repos=$(echo "$repos" | sed 's/^,//')
          echo "matrix={\"repo\":[$repos]}" >> $GITHUB_OUTPUT

  # Job 2: Mencari dan membatalkan workflow di setiap repo target
  cancel-rdp-session:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Find and Cancel Running Workflow in ${{ matrix.repo }}
        id: cancel_run
        run: |
          # Mencari ID workflow RDP (main.yml) yang statusnya sedang berjalan
          RUN_ID=$(gh run list --repo Hazim19/${{ matrix.repo }} --workflow main.yml --status in_progress --limit 1 --json databaseId -q '.[0].databaseId')

          if [[ -z "$RUN_ID" ]]; then
            # Jika tidak ada workflow yang berjalan
            echo "No running RDP session found for ${{ matrix.repo }}."
            echo "status=not_found" >> $GITHUB_OUTPUT
          else
            # Jika ditemukan, batalkan workflow tersebut
            echo "Found running session with ID: $RUN_ID. Attempting to cancel..."
            gh run cancel $RUN_ID --repo Hazim19/${{ matrix.repo }}
            echo "status=cancelled" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.ACTION_PAT }}

      - name: Send Stop Confirmation to Telegram
        run: |
          if [[ "${{ steps.cancel_run.outputs.status }}" == "cancelled" ]]; then
            message="✅ Sesi RDP untuk *${{ matrix.repo }}* berhasil dihentikan."
          else
            message="🟡 Tidak ada sesi RDP yang sedang berjalan untuk *${{ matrix.repo }}*."
          fi

          # Menggunakan curl untuk mengirim pesan balasan
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="$message" \
          -d parse_mode="Markdown"
